### ISSUE TITLE
Why do we use this block code?

### ISSUE THREAD

**Issue by BayramInanc** [wickwirew/Shift#4]
****
<img width="687" alt="Screenshot 2023-04-09 at 22 43 51" src="https://user-images.githubusercontent.com/12694849/230793378-9aefd1c6-e570-4ebe-8511-4923f659ddf7.png">
5df9.png">

when we creating snapshot of UIView, why do we check if it is a imageview or not, is it neccassary? I did not understand, and can it make performance slower, I suspect that. Thanks for your effort.

**Comment by wickwirew** [comment]
Its so they resize better. A normal snapshot just copies the rendered bitmap into a new `UIView` and is not a clone of the view. So if an image is upsized/scaled the image resolution can get weird and not look great

**Comment by BayramInanc** [comment]
Thank you, got it
